# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  ripvcs = {
    pname = "ripvcs";
    version = "6ffd0c1890809257fb4aa0c047ce5e66c5c339f4";
    src = fetchgit {
      url = "https://github.com/ErickKramer/ripvcs.git";
      rev = "6ffd0c1890809257fb4aa0c047ce5e66c5c339f4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-ThWTTgWLnuXIUGghcdoaFUQSzIOREJ29M6kD2AaUbrc=";
    };
    date = "2024-09-13";
  };
}
